name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install npm dependencies
        run: npm install

      - name: Bundle install
        run: bundle install

      - name: Run deploy script
        run: |
          git config user.name "dergigi" && git config user.email "dergigi@pm.me"
          npm run gh-pages-deploy